/* Catálogo de fotografías — generado desde los archivos del estudio */
const PHOTOS=[
{f:"boda-01.jpg",c:"boda",l:"Boda",o:"h",r:"001"},
{f:"boda-02.jpg",c:"boda",l:"Boda",o:"s",r:"002"},
{f:"boda-03.jpg",c:"boda",l:"Boda",o:"s",r:"003"},
{f:"boda-04.jpg",c:"boda",l:"Boda",o:"s",r:"004"},
{f:"boda-05.jpg",c:"boda",l:"Boda",o:"s",r:"005"},
{f:"boda-06.jpg",c:"boda",l:"Boda",o:"s",r:"006"},
{f:"boda-07.jpg",c:"boda",l:"Boda",o:"s",r:"007"},
{f:"boda-08.jpg",c:"boda",l:"Boda",o:"s",r:"008"},
{f:"boda-09.jpg",c:"boda",l:"Boda",o:"s",r:"009"},
{f:"boda-10.jpg",c:"boda",l:"Boda",o:"s",r:"010"},
{f:"boda-11.jpg",c:"boda",l:"Boda",o:"v",r:"011"},
{f:"boda-12.jpg",c:"boda",l:"Boda",o:"s",r:"012"},
{f:"boda-13.jpg",c:"boda",l:"Boda",o:"s",r:"013"},
{f:"boda-bn-01.jpg",c:"boda-bn",l:"Boda B/N",o:"s",r:"014"},
{f:"boda-bn-02.jpg",c:"boda-bn",l:"Boda B/N",o:"s",r:"015"},
{f:"boda-bn-03.jpg",c:"boda-bn",l:"Boda B/N",o:"s",r:"016"},
{f:"graduacion-01.jpg",c:"graduacion",l:"Graduación",o:"h",r:"017"},
{f:"graduacion-02.jpg",c:"graduacion",l:"Graduación",o:"v",r:"018"},
{f:"graduacion-03.jpg",c:"graduacion",l:"Graduación",o:"h",r:"019"},
{f:"graduacion-04.jpg",c:"graduacion",l:"Graduación",o:"v",r:"020"},
{f:"graduacion-05.jpg",c:"graduacion",l:"Graduación",o:"v",r:"021"},
{f:"graduacion-06.jpg",c:"graduacion",l:"Graduación",o:"v",r:"022"},
{f:"graduacion-07.jpg",c:"graduacion",l:"Graduación",o:"h",r:"023"},
{f:"graduacion-08.jpg",c:"graduacion",l:"Graduación",o:"h",r:"024"},
{f:"graduacion-09.jpg",c:"graduacion",l:"Graduación",o:"s",r:"025"},
{f:"graduacion-10.jpg",c:"graduacion",l:"Graduación",o:"h",r:"026"},
{f:"graduacion-11.jpg",c:"graduacion",l:"Graduación",o:"v",r:"027"},
{f:"graduacion-12.jpg",c:"graduacion",l:"Graduación",o:"v",r:"028"},
{f:"graduacion-13.jpg",c:"graduacion",l:"Graduación",o:"v",r:"029"},
{f:"graduacion-14.jpg",c:"graduacion",l:"Graduación",o:"v",r:"050"},
{f:"baby-shower-01.jpg",c:"baby-shower",l:"Baby Shower",o:"h",r:"030"},
{f:"baby-shower-02.jpg",c:"baby-shower",l:"Baby Shower",o:"h",r:"031"},
{f:"baby-shower-03.jpg",c:"baby-shower",l:"Baby Shower",o:"s",r:"032"},
{f:"baby-shower-04.jpg",c:"baby-shower",l:"Baby Shower",o:"h",r:"033"},
{f:"baby-shower-05.jpg",c:"baby-shower",l:"Baby Shower",o:"h",r:"034"},
{f:"retrato-01.jpg",c:"retrato",l:"Retrato",o:"h",r:"035"},
{f:"retrato-02.jpg",c:"retrato",l:"Retrato",o:"h",r:"036"},
{f:"retrato-03.jpg",c:"retrato",l:"Retrato",o:"s",r:"037"},
{f:"retrato-04.jpg",c:"retrato",l:"Retrato",o:"h",r:"038"},
{f:"retrato-05.jpg",c:"retrato",l:"Retrato",o:"v",r:"039"},
{f:"retrato-06.jpg",c:"retrato",l:"Retrato",o:"v",r:"040"},
{f:"retrato-07.jpg",c:"retrato",l:"Retrato",o:"v",r:"041"},
{f:"retrato-08.jpg",c:"retrato",l:"Retrato",o:"v",r:"042"},
{f:"retrato-09.jpg",c:"retrato",l:"Retrato",o:"v",r:"043"},
{f:"retrato-10.jpg",c:"retrato",l:"Retrato",o:"s",r:"044"},
{f:"retrato-11.jpg",c:"retrato",l:"Retrato",o:"v",r:"045"},
{f:"retrato-12.jpg",c:"retrato",l:"Retrato",o:"v",r:"046"},
{f:"retrato-13.jpg",c:"retrato",l:"Retrato",o:"s",r:"047"},
{f:"retrato-14.jpg",c:"retrato",l:"Retrato",o:"s",r:"048"},
{f:"retrato-15.jpg",c:"retrato",l:"Retrato",o:"v",r:"049"}
];
